"""init schema

Revision ID: cef43c3a8418
Revises: 
Create Date: 2026-09-09 13:59:00.976998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cef43c3a8418'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('name_bn', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('upazila', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diseases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_bn', sa.String(length=120), nullable=False),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('consent_analytics', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('field_workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('image_ref', sa.String(length=500), nullable=True),
    sa.Column('symptoms_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('online', 'offline', name='diagnosis_source'), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('AUTO_RESOLVED', 'NEEDS_REVIEW', 'VERIFIED', name='diagnosis_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_plots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('label_bn', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('action_bn', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('organic', 'low_chemical', 'chemical', name='treatment_category'), nullable=False),
    sa.Column('cost_level', sa.Integer(), nullable=False),
    sa.Column('effectiveness_rating', sa.Integer(), nullable=False),
    sa.Column('safety_notes_bn', sa.Text(), nullable=True),
    sa.Column('availability_notes_bn', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_treatments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('treatment_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('field_worker_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'EDITED', name='review_status'), nullable=False),
    sa.Column('verified_notes_bn', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['field_worker_id'], ['field_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expert_reviews')
    op.drop_table('diagnosis_treatments')
    op.drop_table('diagnosis_candidates')
    op.drop_table('treatments')
    op.drop_table('symptoms')
    op.drop_table('farm_plots')
    op.drop_table('diagnoses')
    op.drop_table('field_workers')
    op.drop_table('farmers')
    op.drop_table('diseases')
    op.drop_table('regions')
    op.drop_table('crops')
    # ### end Alembic commands ###
